--- #YAML:1.0
name:               WWW-FastPass
version:            0.04
abstract:           Get Satisfaction FastPass functions
author:
    - Tom Harrison <tomhrr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::SHA1:  0
    Net::OAuth:    0
    URI:           0
resources:
    repository:  https://github.com/tomhrr/p5-WWW-FastPass
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
